---
- name: Deploy Angular App
  hosts: webservers
  become: yes

  tasks:

    - name: Clone Repository
      git:
        repo: https://github.com/piyushpingle55/TestAngularApp.git
        dest: /opt/angular-app
        version: main

    - name: Install Dependencies
      command: npm install
      args:
        chdir: /opt/angular-app

    - name: Build Application
      command: npm run build
      args:
        chdir: /opt/angular-app

    - name: Copy Build Files
      copy:
        src: /opt/angular-app/dist/
        dest: /var/www/html/
        remote_src: yes